DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS versions CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE authors (
	id SERIAL PRIMARY KEY,
	given_name VARCHAR(255) NOT NULL, 
	surname VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	created_at TIMESTAMP
);

CREATE TABLE documents (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	created_at TIMESTAMP
);

CREATE TABLE versions (
	id SERIAL PRIMARY KEY,
	blurb VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	author_id INTEGER REFERENCES authors NOT NULL,
	document_id INTEGER REFERENCES documents NOT NULL,
	created_at TIMESTAMP
);

CREATE TABLE comments (
	id SERIAL PRIMARY KEY,
	commentary TEXT NOT NULL,
	version_id INTEGER REFERENCES versions NOT NULL,
	created_at TIMESTAMP
);